from __future__ import annotations

ALGORITHM_VERSION = "1.0.0"

GOAL_CUSTOMER_REACTIVATION = "Customer Reactivation"
GOAL_OVERSTOCK_CLEARANCE = "Overstock Clearance"
GOAL_REACTIVATION_OVERSTOCK = "Reactivation + Overstock"
GOALS = (
    GOAL_CUSTOMER_REACTIVATION,
    GOAL_OVERSTOCK_CLEARANCE,
    GOAL_REACTIVATION_OVERSTOCK,
)

SOURCE_API = "API"
SOURCE_DESK = "Desk"
SOURCE_N8N = "n8n"
SOURCE_MCP = "MCP"
SOURCE_SCHEDULER = "Scheduler"
SOURCES = (SOURCE_API, SOURCE_DESK, SOURCE_N8N, SOURCE_MCP, SOURCE_SCHEDULER)

RUN_STATUS_RUNNING = "Running"
RUN_STATUS_COMPLETED = "Completed"
RUN_STATUS_FAILED = "Failed"
RUN_STATUSES = (RUN_STATUS_RUNNING, RUN_STATUS_COMPLETED, RUN_STATUS_FAILED)

RECOMMENDATION_STATUS_PROPOSED = "Proposed"
RECOMMENDATION_STATUS_REJECTED = "Rejected"
RECOMMENDATION_STATUS_ACTIVATED = "Activated"
RECOMMENDATION_STATUS_EVALUATED = "Evaluated"
RECOMMENDATION_STATUSES = (
    RECOMMENDATION_STATUS_PROPOSED,
    RECOMMENDATION_STATUS_REJECTED,
    RECOMMENDATION_STATUS_ACTIVATED,
    RECOMMENDATION_STATUS_EVALUATED,
)

REASON_REACTIVATION = "REACTIVATION"
REASON_OVERSTOCK = "OVERSTOCK"

BREAK_EVEN_SAFETY_FACTOR = 1.05
FLOAT_TOLERANCE = 1e-9
